<a href="https://colab.research.google.com/github/tejasrajguru2003-dot/Breast_Cancer_Classification/blob/main/Copy_of_Exploratory_Data_Analysis(EDA)_use_case.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
#loading breast cancer dataset from csv file to pandas data frame

In [5]:
import pandas as pd
breast_cancer_data = pd.read_csv('/content/data-selected-columns.csv1.csv')

In [6]:
breast_cancer_data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430

In [7]:
# Check for missing values
missing_values = breast_cancer_data.isnull().sum()
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
id                     0
diagnosis              0
radius_mean            0
texture_mean           0
perimeter_mean         0
area_mean              0
smoothness_mean        0
compactness_mean       0
concavity_mean         0
concave points_mean    0
dtype: int64

In [8]:
breast_cancer_data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430

In [9]:
breast_cancer_data.shape

(569, 10)

In [10]:
breast_cancer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   569 non-null    int64
 1   diagnosis            569 non-null    object
 2   radius_mean          569 non-null    float64
 3   texture_mean         569 non-null    float64
 4   perimeter_mean       569 non-null    float64
 5   area_mean            569 non-null    float64
 6   smoothness_mean      569 non-null    float64
 7   compactness_mean     569 non-null    float64
 8   concavity_mean       569 non-null    float64
 9   concave points_mean  569 non-null    float64
dtypes: float64(8), int64(1), object(1)
memory usage: 44.6+ KB

In [11]:
breast_cancer_data.drop(columns='id',axis=1,inplace=True)

In [12]:
breast_cancer_data.isnull().sum()

diagnosis              0
radius_mean            0
texture_mean           0
perimeter_mean         0
area_mean              0
smoothness_mean        0
compactness_mean       0
concavity_mean         0
concave points_mean    0
dtype: int64

In [13]:
breast_cancer_data.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200

In [14]:
breast_cancer_data['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [15]:
lable_encode=LabelEncoder()

In [16]:
lables=lable_encode.fit_transform(breast_cancer_data['diagnosis'])

In [17]:
breast_cancer_data['target']=lables

In [18]:
breast_cancer_data.drop(columns='diagnosis',axis=1,inplace=True)

In [19]:
breast_cancer_data.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,1
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,1
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,1
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,1
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,1

In [20]:
breast_cancer_data['target'].value_counts()

target
0    357
1    212
Name: count, dtype: int64

In [21]:
breast_cancer_data.groupby('target').mean()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean
target,,,,,,,,
0,12.146524,17.914762,78.075406,462.790196,0.092478,0.080085,0.046058,0.025717
1,17.462830,21.604906,115.365377,978.376415,0.102898,0.145188,0.160775,0.087990